### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by Quasso**
Hi there mate, 

We've just been exploring a new cross-platform app solution at work and I arrived at your repo, I really liked what I saw but noticed certain things were out of date. I wanted to get things as up to date as possible while maintaining the original build, so I made some tweaks for the baseline of our project.

I figured it'd be nice to fire this over to you, for your consideration. Some key changes:
- Upgraded from TSD to Typings, given that TSD is deprecated in favour of typings
- Upgraded Node version to latest stable, v6.2.2
- Upgraded ionic to latest stable release, v1.3.1
- Upgraded TypeScript to latest stable, v1.8.9
- Upgraded Angular dependencies to 1.5.x versions, actually 1.5.3 since some of the bower dependencies hinged on this unfortunately (for ionic)
- Added some custom typings for definitions that appeared to be missing
- As a note, I had to alter some of the build process ever so slightly. I also switched the TS compilation tasks a little, one of which is a node package which I find provides nicer logging during compilation phase and offers greater ability to customise TSC's parameters

Let me know what you think!

Appreciate your work on this--it is a great starter project and full with useful, well-written utilities and helpers.

### CODE REVIEW

**Comment by Quasso** [comment]
Whoops, overlooked a few things here, just making little changes when I get a chance--my head's kind of elsewhere at the moment since I'm focused on other things. Initially forgot to update travis config and then had some issues with the lint task--I will debug locally to get working and commit later ;)

**Comment by Quasso** [comment]
There we go!

**Comment by Justin-Credible** [comment]
Hello! Thanks for your input!

The plan was to migrate to typings, but I'm waiting to see how this pans out:
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

The ability to install type definitions directly from npm without using a separate tool would be great.

**Comment by Quasso** [comment]
Hey,

This looks absolutely great--I look forward to that becoming a reality. It'll be trivial I'd imagine to add support for that.

Regardless, as things stand, Typings is the only real solution right now. Is there a particular reason you don't think this merge would make a useful update for now? There were one or two other things I tweaked with the build process after this, including adding a more verbose SASS build process with support for globbed imports in SASS. Let me know if you'd like me to pick that work out and push it here :)

**Comment by Justin-Credible** [comment]
Hello again, sorry for the delayed reply.

I looked into adding support for typings again last week and decided to hold off for now for a couple of reasons.

---

Firstly, IMHO the main benefit of typings over tsd is the paradigm shift in how type definitions are written. This means moving away from ambient modules that pollute the global namespace towards external modules that are well contained. This is an excellent change!

Unfortunately, most of the type definitions in use by this project haven't been converted to external modules when I checked. So, while typings can include the existing ambient modules from the definitely typed repository, we'd still be using the original ambient modules.

---

Secondly, I found that the typings CLI tool isn't as flexible as tsd is.

Currently, this project has two tsd configuration files: `tsd.json` for type definitions used by the application and `tsd.tests.json` for type definitions specific to the unit testing.

The tsd command line tool allows you to specify which configuration file to use (`tsd rebundle --config tsd.tests.json`) while typings does not. So I would have to move from the current directory structure of:

```
│   tsd.json
│   tsd.tests.json
│
├───typings
└───typings-tests
```

to the the following directory structure (which is more convoluted IMO):

```
├───typings-app
│   │   typings.json
│   │
│   └───typings
└───typings-tests
    │   typings.json
    │
    └───typings
```

This also makes it more work to run the CLI tool as you have to cd into the appropriate directory before running the command.

---

I'll eventually move to typings are more type definitions become available as external modules and/or the tool becomes more flexible.

**Pull request closed without merging**
